[package]
name = "changelog-v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.32.0"
tokio = { version = "1.35.0", features = ["full"] }
petgraph = "0.6.4"
lazy_static = "1.4.0"